/*******************************************************
 * DEMO — brand, catalog, and builder data
 *
 * Swap products, prices, images, and contact details here.
 * Image files live in /images.
 *******************************************************/

export const SITE = {
  name: "Demo",
  tagline: "Quality Tech. Smarter Prices.",
  subtitle:
    "Pre-owned PCs, laptops, phones and components — plus custom PC builds made for you.",
  phone: "+1 (555) 014-2290",
  phoneHref: "tel:+15550142290",
  whatsapp: "15550142290",
  email: "hello@demo.store",
  addressLine: "Unit 4, 180 Hardware Street",
  city: "Workshop & Showroom",
  hours: "Mon–Sat, 10:00–18:00",
  warranty: "90-day warranty",
  instagram: "#",
  facebook: "#",
};

export const CATEGORIES = [
  {
    id: "pcs",
    name: "Second-Hand PCs",
    description: "Tested desktops for work, study, and play — ready to ship.",
    image: "images/cat-pcs.jpg",
    href: "shop.html?category=pcs",
  },
  {
    id: "laptops",
    name: "Laptops",
    description: "Gaming and ultrathin notebooks, graded and battery-checked.",
    image: "images/cat-laptops.jpg",
    href: "shop.html?category=laptops",
  },
  {
    id: "phones",
    name: "Phones",
    description: "Current-gen iPhones and Androids with honest condition notes.",
    image: "images/cat-phones.jpg",
    href: "shop.html?category=phones",
  },
  {
    id: "components",
    name: "PC Components",
    description: "GPUs, CPUs, memory and storage pulled, tested, and listed.",
    image: "images/cat-components.jpg",
    href: "shop.html?category=components",
  },
  {
    id: "custom",
    name: "Custom PC Builds",
    description: "Tell us the budget. We configure, assemble, and burn-in.",
    image: "images/cat-builds.jpg",
    href: "builder.html",
  },
];

export const PRODUCTS = [
  {
    id: "pulse-3060",
    name: "Gaming PC — Ryzen 5 / RTX 3060",
    shortName: "Pulse 3060",
    category: "pcs",
    condition: "Excellent",
    price: 54999,
    originalPrice: 74999,
    image: "images/pc-ryzen5-3060.jpg",
    gallery: ["images/pc-ryzen5-3060.jpg", "images/cat-pcs.jpg"],
    specs: ["Ryzen 5 5600", "RTX 3060 12GB", "16GB DDR4", "1TB NVMe"],
    specList: {
      CPU: "AMD Ryzen 5 5600",
      GPU: "GeForce RTX 3060 12GB",
      Memory: "16GB DDR4-3200",
      Storage: "1TB NVMe SSD",
      Motherboard: "B550",
      PSU: "650W 80+ Bronze",
      Case: "Mesh mid-tower",
      OS: "Windows 11 Pro",
    },
    stock: 3,
    featured: true,
    warranty: "90 days",
    notes: "Clean interior, no dents. Light dusting on the top mesh only.",
    tested: ["POST", "3DMark", "Storage health", "Thermals"],
  },
  {
    id: "apex-3070",
    name: "Gaming PC — Ryzen 7 / RTX 3070",
    shortName: "Apex 3070",
    category: "pcs",
    condition: "Very Good",
    price: 74999,
    originalPrice: 99999,
    image: "images/pc-highend.jpg",
    gallery: ["images/pc-highend.jpg", "images/cat-pcs.jpg"],
    specs: ["Ryzen 7 5700X", "RTX 3070 8GB", "32GB DDR4", "1TB NVMe"],
    specList: {
      CPU: "AMD Ryzen 7 5700X",
      GPU: "GeForce RTX 3070 8GB",
      Memory: "32GB DDR4-3600",
      Storage: "1TB NVMe SSD",
      Motherboard: "B550",
      PSU: "750W 80+ Gold",
      Case: "Tempered glass mid-tower",
      OS: "Windows 11 Pro",
    },
    stock: 2,
    featured: false,
    warranty: "90 days",
    notes: "Faint scuff on the rear I/O shield. Glass panel is unmarked.",
    tested: ["POST", "FurMark 30 min", "Storage health", "Thermals"],
  },
  {
    id: "titan-4070",
    name: "Creator PC — i7 / RTX 4070",
    shortName: "Titan 4070",
    category: "pcs",
    condition: "Excellent",
    price: 124999,
    originalPrice: 169999,
    image: "images/pc-custom.jpg",
    gallery: ["images/pc-custom.jpg", "images/cat-builds.jpg"],
    specs: ["i7-12700K", "RTX 4070 12GB", "32GB DDR4", "2TB NVMe"],
    specList: {
      CPU: "Intel Core i7-12700K",
      GPU: "GeForce RTX 4070 12GB",
      Memory: "32GB DDR4-3600",
      Storage: "2TB NVMe SSD",
      Motherboard: "Z690",
      PSU: "850W 80+ Gold",
      Cooling: "240mm AIO",
      OS: "Windows 11 Pro",
    },
    stock: 1,
    featured: false,
    warranty: "90 days",
    notes: "One-owner workstation. Cable management redone in-house.",
    tested: ["POST", "Blender", "3DMark", "Overnight burn-in"],
  },
  {
    id: "office-i5",
    name: "Compact Office PC — i5 / 16GB",
    shortName: "Office i5",
    category: "pcs",
    condition: "Good",
    price: 18999,
    originalPrice: 28999,
    image: "images/pc-office.jpg",
    gallery: ["images/pc-office.jpg"],
    specs: ["i5-10400", "UHD Graphics", "16GB DDR4", "512GB SSD"],
    specList: {
      CPU: "Intel Core i5-10400",
      GPU: "Intel UHD 630",
      Memory: "16GB DDR4-2666",
      Storage: "512GB SATA SSD",
      Form: "Small form-factor",
      OS: "Windows 11 Pro",
    },
    stock: 5,
    featured: false,
    warranty: "90 days",
    notes: "Visible wear on the front bezel. Fully functional, quiet fans.",
    tested: ["POST", "Office suite", "Storage health"],
  },
  {
    id: "tuf-4060",
    name: "Gaming Laptop — RTX 4060",
    shortName: "TUF 4060",
    category: "laptops",
    condition: "Excellent",
    price: 120000,
    originalPrice: 154990,
    image: "images/laptop-4060.jpg",
    gallery: ["images/laptop-4060.jpg", "images/cat-laptops.jpg"],
    specs: ["i7-13620H", "RTX 4060 8GB", "16GB DDR5", "1TB NVMe", "15.6\" 144Hz"],
    specList: {
      CPU: "Intel Core i7-13620H",
      GPU: "GeForce RTX 4060 8GB",
      Memory: "16GB DDR5",
      Storage: "1TB NVMe SSD",
      Display: "15.6\" 144Hz FHD",
      Battery: "91% health",
      OS: "Windows 11 Home",
    },
    stock: 2,
    featured: true,
    warranty: "90 days",
    notes: "Keyboard and chassis are clean. Screen has no backlight bleed of note.",
    tested: ["Battery cycle", "Keyboard", "Ports", "Gaming load"],
  },
  {
    id: "legion-3060",
    name: "Gaming Laptop — RTX 3060",
    shortName: "Legion 3060",
    category: "laptops",
    condition: "Very Good",
    price: 84999,
    originalPrice: 114999,
    image: "images/laptop-3060.jpg",
    gallery: ["images/laptop-3060.jpg"],
    specs: ["Ryzen 7 5800H", "RTX 3060 6GB", "16GB DDR4", "512GB NVMe"],
    specList: {
      CPU: "AMD Ryzen 7 5800H",
      GPU: "GeForce RTX 3060 6GB",
      Memory: "16GB DDR4",
      Storage: "512GB NVMe SSD",
      Display: "15.6\" 165Hz FHD",
      Battery: "84% health",
      OS: "Windows 11 Home",
    },
    stock: 2,
    featured: false,
    warranty: "90 days",
    notes: "Light wear on the palm rest. WASD keys show gentle shine.",
    tested: ["Battery cycle", "Keyboard", "Ports", "Gaming load"],
  },
  {
    id: "macbook-air-m1",
    name: "MacBook Air M1 — 8GB / 256GB",
    shortName: "MacBook Air M1",
    category: "laptops",
    condition: "Excellent",
    price: 49999,
    originalPrice: 79999,
    image: "images/laptop-slim.jpg",
    gallery: ["images/laptop-slim.jpg"],
    specs: ["Apple M1", "8GB unified", "256GB SSD", "13.3\" Retina"],
    specList: {
      Chip: "Apple M1",
      Memory: "8GB unified",
      Storage: "256GB SSD",
      Display: "13.3\" Retina",
      Battery: "92% health",
      CycleCount: "218",
      OS: "macOS",
    },
    stock: 4,
    featured: false,
    warranty: "90 days",
    notes: "Space Gray. Near-invisible hairline on the lid, not visible in use.",
    tested: ["Battery", "Keyboard", "Trackpad", "Display"],
  },
  {
    id: "xps-13",
    name: "Ultrabook — i7 / 16GB / 512GB",
    shortName: "XPS-class 13",
    category: "laptops",
    condition: "Very Good",
    price: 52999,
    originalPrice: 84999,
    image: "images/cat-laptops.jpg",
    gallery: ["images/cat-laptops.jpg"],
    specs: ["i7-1165G7", "16GB LPDDR4x", "512GB NVMe", "13.4\" FHD+"],
    specList: {
      CPU: "Intel Core i7-1165G7",
      GPU: "Iris Xe",
      Memory: "16GB LPDDR4x",
      Storage: "512GB NVMe SSD",
      Display: "13.4\" FHD+",
      Battery: "87% health",
      OS: "Windows 11 Pro",
    },
    stock: 3,
    featured: false,
    warranty: "90 days",
    notes: "Carbon-fiber palm rest has light polish. Screen is bright and even.",
    tested: ["Battery", "Keyboard", "Ports", "Display"],
  },
  {
    id: "iphone-13-128",
    name: "iPhone 13 — 128GB",
    shortName: "iPhone 13",
    category: "phones",
    condition: "Excellent",
    price: 34999,
    originalPrice: 54999,
    image: "images/iphone-13.jpg",
    gallery: ["images/iphone-13.jpg"],
    specs: ["A15 Bionic", "128GB", "Midnight", "Battery 91%"],
    specList: {
      Chip: "A15 Bionic",
      Storage: "128GB",
      Color: "Midnight",
      Battery: "91% health",
      FaceID: "Working",
      Unlocked: "Yes",
    },
    stock: 6,
    featured: true,
    warranty: "90 days",
    notes: "No scratches on the display. Frame is clean. True Tone working.",
    tested: ["Battery", "Cameras", "Face ID", "Radios"],
  },
  {
    id: "galaxy-s23",
    name: "Samsung Galaxy S23 — 128GB",
    shortName: "Galaxy S23",
    category: "phones",
    condition: "Excellent",
    price: 36999,
    originalPrice: 64999,
    image: "images/phone-samsung.jpg",
    gallery: ["images/phone-samsung.jpg", "images/cat-phones.jpg"],
    specs: ["Snapdragon 8 Gen 2", "128GB", "Phantom Black", "Battery 93%"],
    specList: {
      Chip: "Snapdragon 8 Gen 2",
      Storage: "128GB",
      Color: "Phantom Black",
      Battery: "93% health",
      Biometrics: "Working",
      Unlocked: "Yes",
    },
    stock: 4,
    featured: true,
    warranty: "90 days",
    notes: "Original box not included. Glass and frame are in excellent shape.",
    tested: ["Battery", "Cameras", "Fingerprint", "5G"],
  },
  {
    id: "iphone-14-128",
    name: "iPhone 14 — 128GB",
    shortName: "iPhone 14",
    category: "phones",
    condition: "Very Good",
    price: 42999,
    originalPrice: 64999,
    image: "images/iphone-14.jpg",
    gallery: ["images/iphone-14.jpg"],
    specs: ["A15 Bionic", "128GB", "Starlight", "Battery 88%"],
    specList: {
      Chip: "A15 Bionic",
      Storage: "128GB",
      Color: "Starlight",
      Battery: "88% health",
      FaceID: "Working",
      Unlocked: "Yes",
    },
    stock: 3,
    featured: false,
    warranty: "90 days",
    notes: "Micro-marks on the aluminum band. Screen is unblemished.",
    tested: ["Battery", "Cameras", "Face ID", "Radios"],
  },
  {
    id: "pixel-7",
    name: "Google Pixel 7 — 128GB",
    shortName: "Pixel 7",
    category: "phones",
    condition: "Good",
    price: 18999,
    originalPrice: 34999,
    image: "images/pixel-7.jpg",
    gallery: ["images/pixel-7.jpg"],
    specs: ["Google Tensor G2", "128GB", "Obsidian", "Battery 86%"],
    specList: {
      Chip: "Google Tensor G2",
      Storage: "128GB",
      Color: "Obsidian",
      Battery: "86% health",
      Unlocked: "Yes",
    },
    stock: 3,
    featured: false,
    warranty: "90 days",
    notes: "Visible scuffs on the camera bar. Display is clean, no burn-in.",
    tested: ["Battery", "Cameras", "Fingerprint", "Radios"],
  },
  {
    id: "galaxy-s22",
    name: "Samsung Galaxy S22 — 128GB",
    shortName: "Galaxy S22",
    category: "phones",
    condition: "Very Good",
    price: 24999,
    originalPrice: 44999,
    image: "images/galaxy-s23.jpg",
    gallery: ["images/galaxy-s23.jpg"],
    specs: ["Snapdragon 8 Gen 1", "128GB", "Graphite", "Battery 89%"],
    specList: {
      Chip: "Snapdragon 8 Gen 1",
      Storage: "128GB",
      Color: "Graphite",
      Battery: "89% health",
      Unlocked: "Yes",
    },
    stock: 2,
    featured: false,
    warranty: "90 days",
    notes: "Light wear around the charging port. Cameras test clean.",
    tested: ["Battery", "Cameras", "Fingerprint", "5G"],
  },
  {
    id: "iphone-12",
    name: "iPhone 12 — 64GB",
    shortName: "iPhone 12",
    category: "phones",
    condition: "Good",
    price: 21999,
    originalPrice: 39999,
    image: "images/iphone-13.jpg",
    gallery: ["images/iphone-13.jpg"],
    specs: ["A14 Bionic", "64GB", "Black", "Battery 84%"],
    specList: {
      Chip: "A14 Bionic",
      Storage: "64GB",
      Color: "Black",
      Battery: "84% health",
      FaceID: "Working",
      Unlocked: "Yes",
    },
    stock: 4,
    featured: false,
    warranty: "90 days",
    notes: "Fine hairlines on the frame. Screen protector installed.",
    tested: ["Battery", "Cameras", "Face ID", "Radios"],
  },
  {
    id: "rtx-4070",
    name: "GeForce RTX 4070 12GB",
    shortName: "RTX 4070",
    category: "components",
    condition: "Excellent",
    price: 42999,
    originalPrice: 54999,
    image: "images/rtx-4070.jpg",
    gallery: ["images/rtx-4070.jpg", "images/cat-components.jpg"],
    specs: ["12GB GDDR6X", "Triple-fan", "PCIe 4.0", "3× DP + HDMI"],
    specList: {
      Memory: "12GB GDDR6X",
      Cooler: "Triple-fan",
      Interface: "PCIe 4.0 ×16",
      Outputs: "3× DisplayPort, 1× HDMI",
      Power: "8-pin",
    },
    stock: 2,
    featured: true,
    warranty: "90 days",
    notes: "Fans quiet. Pads and paste inspected. No coil whine under load.",
    tested: ["FurMark", "Artifact check", "Fan curve"],
  },
  {
    id: "rtx-3060",
    name: "GeForce RTX 3060 12GB",
    shortName: "RTX 3060",
    category: "components",
    condition: "Very Good",
    price: 19999,
    originalPrice: 27999,
    image: "images/rtx-4070.jpg",
    gallery: ["images/rtx-4070.jpg"],
    specs: ["12GB GDDR6", "Dual-fan", "PCIe 4.0"],
    specList: {
      Memory: "12GB GDDR6",
      Cooler: "Dual-fan",
      Interface: "PCIe 4.0 ×16",
      Power: "8-pin",
    },
    stock: 4,
    featured: false,
    warranty: "90 days",
    notes: "Minor scuff on the backplate. Benchmarks in spec.",
    tested: ["FurMark", "Artifact check"],
  },
  {
    id: "ryzen-7800x3d",
    name: "AMD Ryzen 7 7800X3D",
    shortName: "7800X3D",
    category: "components",
    condition: "Excellent",
    price: 29999,
    originalPrice: 39999,
    image: "images/cpu.jpg",
    gallery: ["images/cpu.jpg"],
    specs: ["8 cores / 16 threads", "AM5", "3D V-Cache"],
    specList: {
      Cores: "8 cores / 16 threads",
      Socket: "AM5",
      Cache: "96MB 3D V-Cache",
      TDP: "120W",
    },
    stock: 2,
    featured: true,
    warranty: "90 days",
    notes: "Delidded? No. IHS is clean. Sold with original cooler omitted.",
    tested: ["Cinebench", "Prime95 blend"],
  },
  {
    id: "ddr5-32",
    name: "32GB DDR5-6000 (2×16GB)",
    shortName: "32GB DDR5",
    category: "components",
    condition: "Excellent",
    price: 8499,
    originalPrice: 12499,
    image: "images/ram.jpg",
    gallery: ["images/ram.jpg"],
    specs: ["DDR5-6000", "CL30", "Matched kit"],
    specList: {
      Capacity: "32GB (2×16GB)",
      Speed: "DDR5-6000",
      Timing: "CL30",
      Voltage: "1.35V",
    },
    stock: 8,
    featured: true,
    warranty: "90 days",
    notes: "Heatspreaders unmarked. XMP/EXPO profile verified.",
    tested: ["Memtest", "EXPO/XMP"],
  },
  {
    id: "nvme-1tb",
    name: "1TB NVMe SSD",
    shortName: "1TB NVMe",
    category: "components",
    condition: "Very Good",
    price: 5499,
    originalPrice: 7999,
    image: "images/ssd.jpg",
    gallery: ["images/ssd.jpg"],
    specs: ["PCIe 4.0", "1TB", "82% life remaining"],
    specList: {
      Interface: "PCIe 4.0 NVMe",
      Capacity: "1TB",
      Health: "82% life remaining",
      Form: "M.2 2280",
    },
    stock: 10,
    featured: true,
    warranty: "90 days",
    notes: "Secure-erased. SMART health is strong with moderate wear.",
    tested: ["SMART", "CrystalDisk"],
  },
  {
    id: "nvme-2tb",
    name: "2TB NVMe SSD",
    shortName: "2TB NVMe",
    category: "components",
    condition: "Excellent",
    price: 9999,
    originalPrice: 14999,
    image: "images/ssd.jpg",
    gallery: ["images/ssd.jpg"],
    specs: ["PCIe 4.0", "2TB", "94% life remaining"],
    specList: {
      Interface: "PCIe 4.0 NVMe",
      Capacity: "2TB",
      Health: "94% life remaining",
      Form: "M.2 2280",
    },
    stock: 6,
    featured: false,
    warranty: "90 days",
    notes: "Lightly used. Secure-erased before listing.",
    tested: ["SMART", "CrystalDisk"],
  },
  {
    id: "b650",
    name: "B650 ATX Motherboard",
    shortName: "B650",
    category: "components",
    condition: "Very Good",
    price: 14999,
    originalPrice: 19999,
    image: "images/cat-components.jpg",
    gallery: ["images/cat-components.jpg"],
    specs: ["AM5", "DDR5", "PCIe 5.0 ×16", "Wi-Fi 6"],
    specList: {
      Socket: "AM5",
      Memory: "DDR5",
      Form: "ATX",
      Networking: "2.5GbE + Wi-Fi 6",
    },
    stock: 3,
    featured: false,
    warranty: "90 days",
    notes: "I/O shield included. No bent pins. BIOS updated.",
    tested: ["POST", "All slots", "BIOS flash"],
  },
  {
    id: "psu-750",
    name: "750W Gold Modular PSU",
    shortName: "750W Gold",
    category: "components",
    condition: "Excellent",
    price: 7999,
    originalPrice: 11999,
    image: "images/cat-components.jpg",
    gallery: ["images/cat-components.jpg"],
    specs: ["750W", "80+ Gold", "Fully modular"],
    specList: {
      Wattage: "750W",
      Efficiency: "80+ Gold",
      Cables: "Fully modular",
      WarrantyNote: "Tested under load",
    },
    stock: 5,
    featured: false,
    warranty: "90 days",
    notes: "Sleeved cables included. Rails stable at 100% load.",
    tested: ["Load test", "Ripple"],
  },
  {
    id: "ryzen-5600",
    name: "AMD Ryzen 5 5600",
    shortName: "Ryzen 5 5600",
    category: "components",
    condition: "Good",
    price: 7499,
    originalPrice: 12999,
    image: "images/cpu.jpg",
    gallery: ["images/cpu.jpg"],
    specs: ["6 cores / 12 threads", "AM4", "Wraith cooler"],
    specList: {
      Cores: "6 cores / 12 threads",
      Socket: "AM4",
      TDP: "65W",
      Cooler: "Wraith Stealth included",
    },
    stock: 7,
    featured: false,
    warranty: "90 days",
    notes: "Thermal paste residue cleaned. Pins straight.",
    tested: ["Cinebench", "Idle thermals"],
  },
  {
    id: "aio-360",
    name: "360mm AIO Liquid Cooler",
    shortName: "360mm AIO",
    category: "components",
    condition: "Very Good",
    price: 6999,
    originalPrice: 10999,
    image: "images/pc-highend.jpg",
    gallery: ["images/pc-highend.jpg"],
    specs: ["360mm radiator", "3× fans", "AM4/AM5/LGA1700"],
    specList: {
      Radiator: "360mm",
      Fans: "3 × 120mm",
      Sockets: "AM4, AM5, LGA1700",
    },
    stock: 3,
    featured: false,
    warranty: "90 days",
    notes: "Pump is quiet. Mounting hardware complete.",
    tested: ["Pump", "Leak inspection"],
  },
  {
    id: "build-starter",
    name: "Custom Starter Build",
    shortName: "Starter Build",
    category: "custom",
    condition: "New Build",
    price: 79999,
    originalPrice: null,
    image: "images/pc-ryzen5-3060.jpg",
    gallery: ["images/pc-ryzen5-3060.jpg"],
    specs: ["Ryzen 5 7600", "RTX 4060", "32GB DDR5", "1TB NVMe"],
    specList: {
      CPU: "Ryzen 5 7600",
      GPU: "RTX 4060 8GB",
      Memory: "32GB DDR5-6000",
      Storage: "1TB NVMe",
      Note: "Assembled and burn-in tested to order",
    },
    stock: 99,
    featured: false,
    warranty: "1 year",
    notes: "Configured around 1080p gaming and everyday work. Change any part in the builder.",
    tested: ["Assembly", "24h burn-in"],
  },
  {
    id: "build-gamer",
    name: "Custom Gamer Build",
    shortName: "Gamer Build",
    category: "custom",
    condition: "New Build",
    price: 129999,
    originalPrice: null,
    image: "images/cat-builds.jpg",
    gallery: ["images/cat-builds.jpg", "images/pc-custom.jpg"],
    specs: ["Ryzen 7 7800X3D", "RTX 4070", "32GB DDR5", "2TB NVMe"],
    specList: {
      CPU: "Ryzen 7 7800X3D",
      GPU: "RTX 4070 12GB",
      Memory: "32GB DDR5-6000",
      Storage: "2TB NVMe",
      Note: "Assembled and burn-in tested to order",
    },
    stock: 99,
    featured: false,
    warranty: "1 year",
    notes: "1440p gaming build. Swap parts in the PC Builder to match your budget.",
    tested: ["Assembly", "24h burn-in"],
  },
];

export const REVIEWS = [
  {
    name: "Marcus T.",
    role: "Bought the Pulse 3060",
    rating: 5,
    text: "The Ryzen 5 PC plays everything I throw at it. Interior was spotless and the listing photos matched exactly. Feels like a new machine at a used price.",
  },
  {
    name: "Priya S.",
    role: "iPhone 13 — Excellent",
    rating: 5,
    text: "Battery health was as advertised and Face ID worked out of the box. Grading is honest — that’s rare.",
  },
  {
    name: "Daniel K.",
    role: "Custom editing build",
    rating: 5,
    text: "I sent a budget and a list of apps. They configured a quiet, fast workstation and walked me through every part. The machine arrived burn-in tested.",
  },
  {
    name: "Elena R.",
    role: "Galaxy S23 + support",
    rating: 5,
    text: "WhatsApp replies were fast, and they held the phone until I could collect. After-sales questions were answered without a script. I’ll be back for a laptop.",
  },
];

export const GRADES = [
  {
    id: "Excellent",
    title: "Excellent",
    summary: "Minimal signs of use",
    detail:
      "Looks close to new. No dents, no screen marks, and only the faintest evidence it was owned. Functionally indistinguishable from retail.",
    score: 96,
  },
  {
    id: "Very Good",
    title: "Very Good",
    summary: "Light cosmetic wear",
    detail:
      "A careful previous owner. You may find light scuffs on the chassis or shine on a keyboard — nothing that affects use or photos from a normal distance.",
    score: 82,
  },
  {
    id: "Good",
    title: "Good",
    summary: "Visible signs of use, fully functional",
    detail:
      "Honest wear: hairlines, palmer polish, or a mark on the frame. Every port, camera, and test still passes. The value pick if performance matters more than cosmetics.",
    score: 68,
  },
];

export const BUILDER = {
  cpu: [
    { id: "r5-5600", name: "Ryzen 5 5600", price: 7499, socket: "AM4", memory: "DDR4", tag: "Value", desc: "6 cores · AM4" },
    { id: "r5-7600", name: "Ryzen 5 7600", price: 17999, socket: "AM5", memory: "DDR5", tag: "Sweet spot", desc: "6 cores · AM5" },
    { id: "r7-5800x", name: "Ryzen 7 5800X", price: 13999, socket: "AM4", memory: "DDR4", tag: "", desc: "8 cores · AM4" },
    { id: "r7-7800x3d", name: "Ryzen 7 7800X3D", price: 32999, socket: "AM5", memory: "DDR5", tag: "Gaming", desc: "8 cores · 3D V-Cache" },
    { id: "i5-13400f", name: "Core i5-13400F", price: 15999, socket: "LGA1700", memory: "DDR4", tag: "", desc: "10 cores · Intel" },
    { id: "i7-14700k", name: "Core i7-14700K", price: 34999, socket: "LGA1700", memory: "DDR5", tag: "Creator", desc: "20 cores · Intel" },
  ],
  gpu: [
    { id: "none", name: "Integrated graphics", price: 0, tag: "", desc: "No discrete GPU" },
    { id: "rtx-3060", name: "RTX 3060 12GB", price: 19999, tag: "1080p", desc: "12GB · used, tested" },
    { id: "rtx-4060", name: "RTX 4060 8GB", price: 27999, tag: "Sweet spot", desc: "8GB · 1080p/1440p" },
    { id: "rtx-3070", name: "RTX 3070 8GB", price: 26999, tag: "", desc: "8GB · used, tested" },
    { id: "rtx-4070", name: "RTX 4070 12GB", price: 42999, tag: "1440p", desc: "12GB · ray tracing" },
    { id: "rtx-4070s", name: "RTX 4070 Super", price: 52999, tag: "", desc: "12GB · high refresh" },
  ],
  ram: [
    { id: "16-ddr4", name: "16GB DDR4-3200", price: 3499, type: "DDR4", desc: "2×8GB kit" },
    { id: "32-ddr4", name: "32GB DDR4-3600", price: 5999, type: "DDR4", desc: "2×16GB kit" },
    { id: "32-ddr5", name: "32GB DDR5-6000", price: 8499, type: "DDR5", desc: "2×16GB CL30" },
    { id: "64-ddr5", name: "64GB DDR5-6000", price: 16999, type: "DDR5", desc: "2×32GB kit" },
  ],
  storage: [
    { id: "512", name: "512GB NVMe", price: 3499, desc: "PCIe 4.0" },
    { id: "1tb", name: "1TB NVMe", price: 5499, desc: "PCIe 4.0" },
    { id: "2tb", name: "2TB NVMe", price: 9999, desc: "PCIe 4.0" },
    { id: "2tb-plus", name: "2TB NVMe + 2TB HDD", price: 13999, desc: "Speed + archive" },
  ],
  motherboard: [
    { id: "b550", name: "B550 ATX", price: 8999, socket: "AM4", memory: "DDR4", desc: "Wi-Fi · AM4" },
    { id: "x570", name: "X570 ATX", price: 13999, socket: "AM4", memory: "DDR4", desc: "More lanes · AM4" },
    { id: "b650", name: "B650 ATX", price: 15999, socket: "AM5", memory: "DDR5", desc: "Wi-Fi 6 · AM5" },
    { id: "x670", name: "X670 ATX", price: 24999, socket: "AM5", memory: "DDR5", desc: "Premium I/O · AM5" },
    { id: "b760", name: "B760 ATX", price: 13999, socket: "LGA1700", memory: "DDR4", desc: "Intel DDR4" },
    { id: "z790", name: "Z790 ATX", price: 24999, socket: "LGA1700", memory: "DDR5", desc: "Intel DDR5" },
  ],
  psu: [
    { id: "550", name: "550W Bronze", price: 3999, desc: "Office / iGPU" },
    { id: "650", name: "650W Gold", price: 6499, desc: "RTX 3060 class" },
    { id: "750", name: "750W Gold", price: 8499, desc: "RTX 4070 class" },
    { id: "850", name: "850W Gold modular", price: 10999, desc: "Headroom" },
  ],
  case: [
    { id: "compact", name: "Compact mesh", price: 4499, desc: "Small footprint" },
    { id: "mid-black", name: "Mid-tower black", price: 6499, desc: "Tempered glass" },
    { id: "mid-white", name: "Mid-tower white", price: 7499, desc: "Clean interior" },
    { id: "premium", name: "Premium airflow", price: 11999, desc: "High-end chassis" },
  ],
  cooling: [
    { id: "stock", name: "Stock / bundled", price: 0, desc: "Included cooler" },
    { id: "air", name: "Tower air cooler", price: 2999, desc: "Quiet and simple" },
    { id: "aio240", name: "240mm AIO", price: 6499, desc: "Low temps" },
    { id: "aio360", name: "360mm AIO", price: 9499, desc: "Creator / K-SKU" },
  ],
};

export const BUILDER_DEFAULTS = {
  cpu: "r5-7600",
  gpu: "rtx-4060",
  ram: "32-ddr5",
  storage: "1tb",
  motherboard: "b650",
  psu: "750",
  case: "mid-black",
  cooling: "air",
};

export const BUILDER_PRESETS = [
  {
    id: "starter",
    name: "Starter",
    blurb: "1080p and work",
    priceHint: "Discussions open",
    parts: {
      cpu: "r5-7600",
      gpu: "rtx-4060",
      ram: "32-ddr5",
      storage: "1tb",
      motherboard: "b650",
      psu: "650",
      case: "compact",
      cooling: "air",
    },
  },
  {
    id: "gamer",
    name: "Gamer",
    blurb: "1440p high refresh",
    priceHint: "Discussions open",
    parts: {
      cpu: "r7-7800x3d",
      gpu: "rtx-4070",
      ram: "32-ddr5",
      storage: "2tb",
      motherboard: "b650",
      psu: "750",
      case: "mid-black",
      cooling: "aio240",
    },
  },
  {
    id: "creator",
    name: "Creator",
    blurb: "Edit, 3D, stream",
    priceHint: "Discussions open",
    parts: {
      cpu: "i7-14700k",
      gpu: "rtx-4070s",
      ram: "64-ddr5",
      storage: "2tb-plus",
      motherboard: "z790",
      psu: "850",
      case: "premium",
      cooling: "aio360",
    },
  },
];

export const LABOR = 2499;

export const PRICE_LABEL = "Discussions open";

export function formatPrice() {
  return PRICE_LABEL;
}

export function savings(product) {
  if (!product.originalPrice || product.originalPrice <= product.price) return 0;
  return product.originalPrice - product.price;
}

export function getProduct(id) {
  return PRODUCTS.find((p) => p.id === id);
}

export function productsByCategory(category) {
  if (!category || category === "all") return PRODUCTS;
  return PRODUCTS.filter((p) => p.category === category);
}

export function whatsappLink(message) {
  const text = encodeURIComponent(
    message || "Hi Demo — I’m looking for a device and wanted to ask about availability."
  );
  return `https://wa.me/${SITE.whatsapp}?text=${text}`;
}
